### PR TITLE
fix: adjusting product-comparion and mobile validation

### PR DESCRIPTION
**Pull request by santosluiz000**
#### What problem is this solving?

Adjusting product-comparion layout itens + responsiveness validation

image

And layout itens page

image

#### How should this be manually tested?
1 - Acess: https://luizdev--b2bstore.myvtex.com/
2 - At product search and product page the checkbox should appear to compare products

#### Checklist/Reminders

- [x] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Review by Klynger — CHANGES_REQUESTED** [review]
I didn't understand how to test, could you add some steps of how to see the changes?

[Here is an example of PR of how you could do it](https://github.com/vtex-apps/store-components/pull/836)

**Comment by santosluiz000** [comment]
> I didn't understand how to test, could you add some steps of how to see the changes?
> 
> [Here is an example of PR of how you could do it](https://github.com/vtex-apps/store-components/pull/836)

**Comment by santosluiz000** [comment]
> I didn't understand how to test, could you add some steps of how to see the changes?
> 
> [Here is an example of PR of how you could do it](https://github.com/vtex-apps/store-components/pull/836)

Updated!

**Review by pedrohfsd — APPROVED** [review]
Let's wait for the others but it seems good to me 👍

**Review by fobarros — APPROVED** [review]

**Review by Klynger — APPROVED** [review]

**Pull request merged**
